# Заголовки
headers = {
    'Accept': 'application/json, text/plain, */*',
    'Accept-Language': 'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive', 'Pragma': 'no-cache',
    'Referer': 'https://torgi.gov.ru/new/public/lots/reg',
}

#  Параметры
params = {
    'lotStatus': 'PUBLISHED,APPLICATIONS_SUBMISSION',
    'byFirstVersion': True,
    'withFacets': True,
    'typeTransaction': 'sale',
    'size': 10,
    'sort': 'firstVersionPublicationDate,desc',
}

# Заголовки для Циана
headersCian = {
    'accept': '*/*',
    'accept-language': 'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    'origin': 'https://cian.ru',
    'pragma': 'no-cache',
    'priority': 'u=1, i',
    'referer': 'https://cian.ru/',
}

# Куки для авто ру
cookiesAuto = {
    '_csrf_token': '0275cea19dd583117022f7dad25545a52f439ef61feac4df',
    'yandexuid': '8169110051685964597',
    '_yasc': 'l1QCtacwPNvkvvHTNAOKiXUWqKfW3l7uS62Hqyls4mE3ArLOsodNL2krsnUItKgKUEq7N9Z4',
}

# Заголовки для заголовки
headersAuto = {
    'accept': '*/*',
    'content-type': 'application/json',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0',
    'x-csrf-token': '0275cea19dd583117022f7dad25545a52f439ef61feac4df',
}

# Данные по регионам для торгов
subRF = {'1': {'searchCode': 1, 'name': 'Республика Адыгея'},
         '89': {'searchCode': 85, 'name': 'Ямало-Ненецкий автономный округ'},
         '4': {'searchCode': 2, 'name': 'Республика Алтай'},
         '87': {'searchCode': 84, 'name': 'Чукотский автономный округ'},
         '2': {'searchCode': 3, 'name': 'Республика Башкортостан'},
         '86': {'searchCode': 83, 'name': 'Ханты-Мансийский автономный округ'},
         '3': {'searchCode': 4, 'name': 'Республика Бурятия'},
         '5': {'searchCode': 5, 'name': 'Республика Дагестан'},
         '6': {'searchCode': 6, 'name': 'Республика Ингушетия'},
         '7': {'searchCode': 7, 'name': 'Кабардино-Балкарская Республика'},
         '8': {'searchCode': 8, 'name': 'Республика Калмыкия'},
         '9': {'searchCode': 9, 'name': 'Карачаево-Черкесская Республика'},
         '83': {'searchCode': 82, 'name': 'Ненецкий автономный округ'},
         '10': {'searchCode': 10, 'name': 'Республика Карелия'},
         '79': {'searchCode': 81, 'name': 'Еврейская автономная область'},
         '11': {'searchCode': 11, 'name': 'Республика Коми'},
         '91': {'searchCode': 12, 'name': 'Республика Крым'},
         '92': {'searchCode': 80, 'name': 'г. Севастополь'},
         '12': {'searchCode': 13, 'name': 'Республика Марий Эл'},
         '13': {'searchCode': 14, 'name': 'Республика Мордовия'},
         '78': {'searchCode': 79, 'name': 'г. Санкт-Петербург'},
         '14': {'searchCode': 15, 'name': 'Республика Саха (Якутия)'},
         '15': {'searchCode': 16, 'name': 'Республика Северная Осетия-Алания'},
         '16': {'searchCode': 17, 'name': 'Республика Татарстан'},
         '77': {'searchCode': 78, 'name': 'г. Москва'},
         '17': {'searchCode': 18, 'name': 'Республика Тыва'},
         '18': {'searchCode': 19, 'name': 'Удмуртская Республика'},
         '76': {'searchCode': 77, 'name': 'Ярославская область'},
         '19': {'searchCode': 20, 'name': 'Республика Хакасия'},
         '74': {'searchCode': 76, 'name': 'Челябинская область'},
         '20': {'searchCode': 21, 'name': 'Чеченская Республика'},
         '73': {'searchCode': 75, 'name': 'Ульяновская область'},
         '21': {'searchCode': 22, 'name': 'Чувашская Республика'},
         '72': {'searchCode': 74, 'name': 'Тюменская область'},
         '22': {'searchCode': 23, 'name': 'Алтайский край'},
         '71': {'searchCode': 73, 'name': 'Тульская область'},
         '75': {'searchCode': 24, 'name': 'Забайкальский край'},
         '70': {'searchCode': 72, 'name': 'Томская область'},
         '41': {'searchCode': 25, 'name': 'Камчатский край'},
         '23': {'searchCode': 26, 'name': 'Краснодарский край'},
         '69': {'searchCode': 71, 'name': 'Тверская область'},
         '24': {'searchCode': 27, 'name': 'Красноярский край'},
         '68': {'searchCode': 70, 'name': 'Тамбовская область'},
         '59': {'searchCode': 28, 'name': 'Пермский край'},
         '25': {'searchCode': 29, 'name': 'Приморский край'},
         '67': {'searchCode': 69, 'name': 'Смоленская область'},
         '66': {'searchCode': 68, 'name': 'Свердловская область'},
         '65': {'searchCode': 67, 'name': 'Сахалинская область'},
         '26': {'searchCode': 30, 'name': 'Ставропольский край'},
         '64': {'searchCode': 66, 'name': 'Саратовская область'},
         '63': {'searchCode': 65, 'name': 'Самарская область'},
         '62': {'searchCode': 64, 'name': 'Рязанская область'},
         '61': {'searchCode': 63, 'name': 'Ростовская область'},
         '60': {'searchCode': 62, 'name': 'Псковская область'},
         '58': {'searchCode': 61, 'name': 'Пензенская область'},
         '57': {'searchCode': 60, 'name': 'Орловская область'},
         '56': {'searchCode': 59, 'name': 'Оренбургская область'},
         '55': {'searchCode': 58, 'name': 'Омская область'},
         '54': {'searchCode': 57, 'name': 'Новосибирская область'},
         '53': {'searchCode': 56, 'name': 'Новгородская область'},
         '52': {'searchCode': 55, 'name': 'Нижегородская область'},
         '51': {'searchCode': 54, 'name': 'Мурманская область'},
         '50': {'searchCode': 53, 'name': 'Московская область'},
         '49': {'searchCode': 52, 'name': 'Магаданская область'},
         '48': {'searchCode': 51, 'name': 'Липецкая область'},
         '47': {'searchCode': 50, 'name': 'Ленинградская область'},
         '46': {'searchCode': 49, 'name': 'Курская область'},
         '45': {'searchCode': 48, 'name': 'Курганская область'},
         '44': {'searchCode': 47, 'name': 'Костромская область'},
         '43': {'searchCode': 46, 'name': 'Кировская область'},
         '42': {'searchCode': 45, 'name': 'Кемеровская область'},
         '40': {'searchCode': 44, 'name': 'Калужская область'},
         '39': {'searchCode': 43, 'name': 'Калининградская область'},
         '38': {'searchCode': 42, 'name': 'Иркутская область'},
         '37': {'searchCode': 41, 'name': 'Ивановская область'},
         '36': {'searchCode': 40, 'name': 'Воронежская область'},
         '35': {'searchCode': 39, 'name': 'Вологодская область'},
         '34': {'searchCode': 38, 'name': 'Волгоградская область'},
         '33': {'searchCode': 37, 'name': 'Владимирская область'},
         '32': {'searchCode': 36, 'name': 'Брянская область'},
         '31': {'searchCode': 35, 'name': 'Белгородская область'},
         '30': {'searchCode': 34, 'name': 'Астраханская область'},
         '29': {'searchCode': 33, 'name': 'Архангельская область'},
         '28': {'searchCode': 32, 'name': 'Амурская область'},
         '27': {'searchCode': 31, 'name': 'Хабаровский край'},
         '95': {'searchCode': 107, 'name': 'Херсонская область'},
         '90': {'searchCode': 108, 'name': 'Запорожская область'},
         '94': {'searchCode': 105, 'name': 'Луганская народная Республика'},
         '93': {'searchCode': 106, 'name': 'Донецкая Народная Республика'}, }
